### ISSUE TITLE
Version tags gone missing?

### ISSUE THREAD

**Issue by eikeon** [multiformats/go-multihash#105]
For example, the following no longer seems to work:
    ```go get github.com/multiformats/go-multihash@v1.0.10```

Pretty sure it did when

```github.com/multiformats/go-multihash v1.0.10``` got added to our projects go.mod file.

**Comment by eikeon** [comment]
Ah, and I see some relatively recent commits re: tags see #102 etc

**Comment by raulk** [comment]
We have archived the gx version lineage under the `gx/` tag namespace, and have started from v0.0.1 to avoid unwarranted >= v2 madness with gomod. Please use v0.0.1.

**Comment by eikeon** [comment]
Will do; thank you.
