### ISSUE TITLE
Convert hash to hex hash and vice versa

### ISSUE THREAD

**Issue by teran-mckinney** [multiformats/go-multihash#112]
In the `multihash` CLI it would be nice to be able to easily convert from mutltihash to a more common format.

This could also work to convert a hex SHA256 hash to a multithash, for example, without the file.

So something like: `multihash -convert_to raw QmVrM1N7FQpbvyDosagm5VrMf58EQk8B1C3K87r2sJVE33` or `multihash -convert_to base58 6f9d376ef1f2c899712c49f40d1be02d22ffdc46b2ea9e837a57802a38086bb9`

Also useful as a library, although haven't looked around for that yet.

**Comment by Stebalien** [comment]
The multihash command should probably have a base flag. However, the suggested command just looks like a base conversion tool (not multihash specific).

**Comment by Stebalien** [comment]
Actually, it looks like the command _does_ support specifying the base, just not converting an existing hash. I'm going to close this as out of scope.
