### ISSUE TITLE
Please choose between identity / id and stick to it across all projects

### ISSUE THREAD

**Issue by Gozala** [multiformats/go-multihash#113]
I recently discovered that what go names `id` 

https://github.com/multiformats/go-multihash/blob/0e239d8fa37b597bd150660e5b6845570aa5b833/multihash.go#L92

JS calls identity

https://github.com/multiformats/js-multihash/issues/70

Which is confusing, but then I also discovered that [multicodec table](https://github.com/multiformats/multicodec/blob/master/table.csv) also refers to ` 0x00` as `identity`.

Please pick either name but stick to one across projects otherwise it's very confusing.

**Comment by Stebalien** [comment]
Yeah, it should be "identity".
