### ISSUE TITLE
[enhancement] adding BLAKE3 support

### ISSUE THREAD

**Issue by eleitl** [multiformats/go-multihash#121]
BLAKE3 https://github.com/BLAKE3-team/BLAKE3 is a major improvement (https://medium.com/asecuritysite-when-bob-met-alice/blake3-3716708235ac https://news.ycombinator.com/item?id=22021769 https://news.ycombinator.com/item?id=22003315) on BLAKE2 in regards to speed.

There's a pure Go implementation https://github.com/lukechampine/blake3 though it's not optimized yet. An optimized version will become available in x/crypto at some point.

As an enhancement proposal, it would be nice to have at least preliminary BLAKE3 support in multihash so that downstream like IPFS can start using it.

**Comment by Stebalien** [comment]
I'd like to see some people try to break it first. Much of its speed comes from the assumption that current symmetric algorithms [are too paranoid and have two many rounds](https://eprint.iacr.org/2019/1492.pdf).

**Comment by lzsaver** [comment]
Seems related: https://github.com/zeebo/blake3 https://github.com/connor4312/blake3

**Comment by cryptoquick** [comment]
Is there any way to get a sense of priority on this? It'd be very helpful for my use-case.

Blake3 digests don't need to finish hashing a data stream before it can tell if the data is incorrect. If one single byte is off anywhere in the stream, it'll immediately throw an exception. This also allows IPLD MerkleDAG blocks to be safely made much larger.

**Comment by Stebalien** [comment]
@cryptoquick the codec is 0x1e. Feel free to add support (we can disable it by default).

> Blake3 digests don't need to finish hashing a data stream before it can tell if the data is incorrect. If one single byte is off anywhere in the stream, it'll immediately throw an exception

Source? That sounds impossible of the "the hash function would be broken if that were the case" kind.

**Comment by cryptoquick** [comment]
> @cryptoquick the codec is 0x1e. Feel free to add support (we can disable it by default).

I'm not a Go developer, but I'm glad there's a Multicodec for it.

> Source? That sounds impossible of the "the hash function would be broken if that were the case" kind.

Yeah, it really cool, check it out!
https://github.com/oconnor663/bao

**Comment by aschmahmann** [comment]
> Blake3 digests don't need to finish hashing a data stream before it can tell if the data is incorrect. If one single byte is off anywhere in the stream, it'll immediately throw an exception

This seems like a bit of an exaggeration, but since Blake3 is a tree hash that means that it can have parallelism in computing the hash which generally means more flexibility (e.g. throwing more cores at the hash means faster detection of certain problems, verified streaming, etc.).

**Comment by Stebalien** [comment]
> To get verified streaming, this would probably require changes to the IPLD implementation, also.

Yeah, you can't just verify raw data while hashing. You still need the rest of the hash tree.

**Comment by cryptoquick** [comment]
@aschmahmann Thanks for providing a link to that PR! I'm glad someone already mentioned verified streaming. Handling arbitrarily large block sizes poses a significant technical challenge, so simply adding Blake3 multihashes alone wouldn't solve it for free, but I think it'd be helpful for efforts like that to work towards supporting Blake3, which I guess is why I bring it up, is all.

Do you think supporting Blake3 at some point will be a helpful follow-on to a SHA2-256-only implementation?

**Comment by cryptoquick** [comment]
A very good point! Another feather in SHA-2's cap is that there's relatively widespread hardware acceleration available:
https://en.wikipedia.org/wiki/Intel_SHA_extensions

That said, these things take time, and Protocol Labs is no stranger to futureproofing. I think Blake3 support should be prioritized, even if the priority is quite low. :)

**Comment by divinity76** [comment]
> > A very good point! Another feather in SHA-2's cap is that there's relatively widespread hardware acceleration available:
> > https://en.wikipedia.org/wiki/Intel_SHA_extensions
> > That said, these things take time, and Protocol Labs is no stranger to futureproofing. I think Blake3 support should be prioritized, even if the priority is quite low. :)
> 
> To be fair here, it's great to have CPU extensions. But if the newcomer (BLAKE3 in this case) is simply downright faster then SHA2-256 (even with the use of those CPU extensions) then there is a real potential here for a just a superior hasher. Definitely faster (better is still up for debate).
> 
> For some numbers. I tried BLAKE3 (b3sum) and SHA2-256 (sha256sum) on a ODROID-XU4 (it's still 32 bit) and a Ryzen 4800u. The results surprised me a lot!
> 1.6GB file on the ODROID-XU4
> BLAKE3: 21 seconds.
> SHA2-256: 45 seconds.
> 
> 5.8GB file on the Rezen 4800u
> BLAKE3: 2.2 seconds
> SHA2-256: 3.7 seconds
> 
> Note that subsequent BLAKE3 (b3sum) runs somehow were much faster with a mere ~0.5 seconds. I'm suspecting some caching going on there. So i took the first and slowest timing.
> 
> That's a full on win for BLAKE3 in two wildly different test scenarios, even though SHA2-256 has the benefit of dedicated CPU extensions.

**Comment by divinity76** [comment]
@markg85 
> Note that subsequent BLAKE3 (b3sum) runs somehow were much faster with a mere ~0.5 seconds. I'm suspecting some caching going on there. So i took the first and slowest timing.

Sha256 was CPU-bound, so the IO speed had little-to-no effect on sha256 hashing, while blake3 was IO-bound, so blake3 ran much faster when the file was already in the IO-cache

**Comment by markg85** [comment]
> Sha256 was CPU-bound, so the IO speed had little-to-no effect on sha256 hashing, while blake3 was IO-bound, so blake3 ran much faster when the file was already in the IO-cache

Ahh, so that's what's happening!
I was assuming it to be something like that but didn't bother figuring it out. Thank you for confirming!

The mere fact that this happens does imho mean that BLAKE3 is just superior for today's hardware.

**Comment by markg85** [comment]
Reviving this to keep all info in one place.
I do have go-ipfs 0.11 which has this has supported.

`ipfs add --nocopy --hash blake3 <somefile>`

Fails with:
`Error: potentially insecure hash functions not allowed`

Is that intentional?

**Comment by divinity76** [comment]
> Is that intentional?

no that must be a bug, but probably not a bug in go-multihash..

**Comment by markg85** [comment]
After some searching it looks like this is causing it: https://github.com/ipfs/go-verifcid/blob/master/validate.go
BLAKE3 isn't in the list.

It does have `if code >= mh.BLAKE2B_MIN+19 && code <= mh.BLAKE2B_MAX` which i don't fully get the logic off.. It "seems" like an attempt to allow blake hashes too? not entirely sure.

The repository (go-verifycid) states that it's a temporary one, but searching for it's use in go-ipfs turns out that it's well used: https://github.com/search?q=org%3Aipfs+go-verifcid&type=code

**Comment by divinity76** [comment]
@markg85 yeah i'd recommend filing a bugreport in the go-verifcid repo
