### ISSUE TITLE
Doesn't match gnutools checksums

### ISSUE THREAD

**Issue by rendom** [multiformats/go-multihash#14]
I was testing hashpipe and notice that my checksum from gnutools "sha1sum" and "sha256sum" doesn't match.

Seems as multihash adds 1114 at the beginning?

```
    [d@x][] echo "foobar" | ./multihash -a="sha1"   
    5dsufTcJUcGW6FskA3wHdW2PuP6Hvg
    [d@x][]% echo "foobar" | ./multihash -a="sha1" -e="hex"
    1114988881adc9fc3655077dc2d4d757d480b5ea0e11
    [d@x][]% echo "foobar" | sha1sum                                                          
    988881adc9fc3655077dc2d4d757d480b5ea0e11  -
´´´
```

**Comment by jbenet** [comment]
Hey @rendom -- thanks for asking.

`hashpipe` uses [multihash](https://github.com/jbenet/multihash/), a multi-hash-function digest encoding. The `1114` is a self-identifying prefix:
- `0x11` for sha1
- `0x14` is for 20 bytes (160 bits of sha1)

**Comment by jbenet** [comment]
It may be useful to add a --naked option to the [go-multihash](https://github.com/jbenet/go-multihash/) tool that outputs just the naked hashes... can also do it with `cut`: 

```
echo foobar | multihash -a sha1 -e hex | cut -c 5-45

```
