### ISSUE TITLE
Create a new tag to allow using recent master

### ISSUE THREAD

**Issue by shoce** [multiformats/go-multihash#146]
Running `go build` i get error:
`undefined: "github.com/multiformats/go-multihash".SumStream`

The last tag `v0.0.15` does not include changes implementing `SumStream`.

To use `SumStream` i need to import `github.com/multiformats/go-multihash` with some tag, not a commit id:
`imports github.com/multiformats/go-multihash@73fdad55417c9d9d9bed929e8751a92d572b564a: can only use path@version syntax with 'go get' and 'go install' in module-aware mode`

Please create a new tag that will include `SumStream` func implementation.

**Comment by marten-seemann** [comment]
I have no opinion about when to cut the next release here, just wanted to point out that `go get` works perfectly fine, and should allow you to import a specific commit:
```
❯ go get github.com/multiformats/go-multihash@73fdad55417c9d9d9bed929e8751a92d572b564a
go: downloading github.com/multiformats/go-multihash v0.0.16-0.20210817134118-73fdad55417c
go get: upgraded github.com/multiformats/go-multihash v0.0.15 => v0.0.16-0.20210817134118-73fdad55417c
```

**Comment by shoce** [comment]
Thanks @marten-seemann, I don't know why it did not work before, now it worked.

**Comment by Stebalien** [comment]
I've cut a release anyways.
