### ISSUE TITLE
Separate interface and implementation

### ISSUE THREAD

**Issue by lgierth** [multiformats/go-multihash#25]
Every dependent function that expects or returns a `Multihash`, should be working with the interface instead of the type. This will make it easier to use go-multihash as a library where various dependents can use various versions of go-multihash. Right now you'll occasionally run into `gx/ipfs/<hash>/go-multihash.Multihash is not gx/ipfs/<other-hash>/go-multihash.Multihash`.

The same applies for other multiformats libraries.

**Comment by lgierth** [comment]
And ideally it should be interfaces everywhere! We'll of course end up with a dozen different versions of the same lib in our dependency trees, but updating a library down in the tree won't be as painful as it is now.

**Comment by Stebalien** [comment]
Closing as this would introduce a bunch of allocations/indirection.
