### ISSUE TITLE
test instructions in readme fail

### ISSUE THREAD

**Issue by zippy** [multiformats/go-multihash#40]
I just followed the test instructions in the readme:

  > cd test/ 
  > go build

And this results in a build error:

eric@finkomatic:~/go/src/github.com/multiformats/go-multihash/test$ go build
can't load package: package github.com/multiformats/go-multihash/test: no buildable Go source files in /home/eric/go/src/github.com/multiformats/go-multihash/test

**Comment by Stebalien** [comment]
The readme no longer has those instructions. Fixed by entropy...
