### ISSUE TITLE
Add blake2b support to multihash command

### ISSUE THREAD

**Issue by aslakg** [multiformats/go-multihash#53]
If blake2b is to be the new ipfs default, it would be useful to add it to this tool

**Comment by Kubuxu** [comment]
It already supports blake2b

**Comment by VictorBjelkholm** [comment]
I was confused when I initially tried to find the correct name for `blake2b` in go-ipfs, which happens to be `blake2b-256`. I looked in these two places:

- https://github.com/multiformats/go-multihash/blob/a52a6a4768da72eba89ea7f59f70e9d42ddd3072/multihash.go#L38-L64
- https://github.com/multiformats/go-multihash/blob/a52a6a4768da72eba89ea7f59f70e9d42ddd3072/multihash.go#L87-L145

But I guess blake2b is manually added somewhere. @Kubuxu could you advise where, for future reference?

**Comment by Kubuxu** [comment]
Blake is added by code: https://github.com/multiformats/go-multihash/blob/a52a6a4768da72eba89ea7f59f70e9d42ddd3072/multihash.go#L67-L83

**Comment by aslakg** [comment]
Sorry, I wasn't precise enough. I meant the command line tool, not the module/library.

$ multihash --help
usage: multihash [options] [FILE]
Print or check multihash checksums.
With no FILE, or when FILE is -, read standard input.

Options:
  -a string
    	one of: sha1, sha2-256, sha2-512, sha3 (shorthand) (default "sha2-256")
  -algorithm string
    	one of: sha1, sha2-256, sha2-512, sha3 (default "sha2-256")

$ multihash -algorithm blake2b-256 file.txt 
error: algorithm 'blake2b-256' not [sha1 sha2-256 sha2-512 sha3]

**Comment by Stebalien** [comment]
Support has been added for a reasonable subset. IMO, this is sufficient. If someone needs a new hash, they can open an issue.

**Comment by Stebalien** [comment]
Support has been added for a reasonable subset. IMO, this is sufficient. If someone needs a new hash, they can open an issue.
