### ISSUE TITLE
Incorrect murmur3 hash algorithm

### ISSUE THREAD

**Issue by alanshaw** [multiformats/go-multihash#56]
`murmur3` is listed but should be `murmur3-32` and `murmur3-128`.

/cc @diasdavid

**Comment by diasdavid** [comment]
@pgte mentioned this before and I believe he actually opened an issue in go-ipfs, I was just unable to find it.

If I understand correctly, go-ipfs uses murmur3-128 sliced in half for unixfs sharding and it uses with the multicodec of murmur3. I believe there is no technical reason for not calling it murmur3-128 as well, but @whyrusleeping will be able to confirm.

**Comment by Stebalien** [comment]
Fixed. I've renamed it to murmur3-128.
