### ISSUE TITLE
Faster sha256 and blake2b implementations

### ISSUE THREAD

**Issue by lgierth** [multiformats/go-multihash#61]
https://github.com/minio/sha256-simd

>  Accelerate SHA256 computations in pure Go using AVX512 and AVX2 for Intel and ARM64 for ARM. On AVX512 it provides an up to 8x improvement (over 3 GB/s per core) in comparison to AVX2.
>
> This package is designed as a replacement for crypto/sha256. For Intel CPUs it has two flavors for AVX512 and AVX2 (AVX/SSE are also supported). For ARM CPUs with the Cryptography Extensions, advantage is taken of the SHA2 instructions resulting in a massive performance improvement.
>
> This package uses Golang assembly. The AVX512 version is based on the Intel's "multi-buffer crypto library for IPSec" whereas the other Intel implementations are described in "Fast SHA-256 Implementations on Intel Architecture Processors" by J. Guilford et al.

https://github.com/minio/blake2b-simd

> This package was initially based on the pure go BLAKE2b implementation of Dmitry Chestnykh and merged with the (cgo dependent) AVX optimized BLAKE2 implementation (which in turn is based on the official implementation. It does so by using Go's Assembler for amd64 architectures with a golang only fallback for other architectures.
> 
> In addition to AVX there is also support for AVX2 as well as SSE. Best performance is obtained with AVX2 which gives roughly a 4X performance increase approaching hashing speeds of 1GB/sec on a single core.

**Comment by Stebalien** [comment]
Note: IIRC, the sha256 one is now no faster on CPUs with only AVX2 support (they used to say this in the readme but recently removed it). So, it won't help on my laptop (:.

However, it does support AVX and ARM so it should help on the gateways (which don't have AVX2 support) and embedded/phones.
