### ISSUE TITLE
Consider removing Sum or moving it to a subpackage

### ISSUE THREAD

**Issue by fjl** [multiformats/go-multihash#78]
multihash is an encoding for hash values. go-multihash depends on implementations of all the hash functions because it provides the `Sum` function.

 IMHO hashing and encoding the hash value as a "multihash" are two separate things and shouldn't be in the same Go package. Removing/splitting out `Sum` would make the package much more light-weight because it would reduce non-stdlib dependencies to just github.com/jbenet/base58.

**Comment by fjl** [comment]
Also consider that `Sum` will never be enough: code that hashes data might want to reuse hash objects, write to them as a stream, etc.

**Comment by Stebalien** [comment]
In principle, I agree. Given the number of dependencies on this package, we'd probably just create a new `go-multihash-format` package and create a bunch of type aliases.

However, we probably won't get around to doing this any time soon.

(although having something other than `Sum` really would be nice)

**Comment by Stebalien** [comment]
Went looking for this and realized it was closed. This isn't fixed.

We should:

1. Stop checking for "valid" codes. There's no reason to reject unknown codes.
2. Move the core logic to a separate module.

That way, people can depend on the types when they don't really need to be able to _hash_ things.

**Comment by Stebalien** [comment]
Visiting for triage, I'm closing this in favor of a new issue that succinctly describes the change we'd accept.

**Comment by Stebalien** [comment]
(the issue: https://github.com/multiformats/go-multihash/issues/131)
