### ISSUE TITLE
Add argon2id as a function

### ISSUE THREAD

**Issue by HazCod** [multiformats/go-multihash#86]
https://github.com/golang/crypto/blob/master/argon2/argon2.go

https://github.com/P-H-C/phc-winner-argon2

**Comment by Stebalien** [comment]
This will need a codec here: https://github.com/multiformats/multicodec/. Like blake2b, this'll need a range of multicodecs (sigh).

**Comment by HazCod** [comment]
I implemented it for myself :)
https://github.com/HazCod/gosecurity/tree/master/gohash

**Comment by Stebalien** [comment]
Hm. Actually, this isn't going to work. It looks like Argon2 is a *password*-hashing algorithm build on blake2b. Multihash expects expects `hash(data)` to always produce the same result and is designed for identifying data and/or verifying data integrity. Argon2 generates a new random salt each time it hashes something, leading to a different "hash".

**Comment by HazCod** [comment]
Good point! I will keep my repo.
